version: '3.3'

services:
  inventory:
    container_name: inventory
    build: .
    ports:
      - "8086:8086"
    networks:
      - inventory_network

networks:
  inventory_network:
    driver: bridge